---
- hosts: coprhd
  sudo: yes
  gather_facts: no
  remote_user: root
  vars:
    sudoers:
      shujin

  tasks:
  
  - name: Make sure there is a 'wheel' group
    group: name=wheel state=present

  - name: Add user 
    user: name="{{ sudoers }}" groups=wheel append=yes state=present password=p@ssw0rd createhome=yes system=yes update_password=always

  - name: configure sudoers
    lineinfile: dest=/etc/sudoers line="%wheel ALL=(ALL) ALL" state=present create=yes validate='visudo -cf %s' backup=yes

  - lineinfile: dest=/etc/sudoers line="{{ sudoers }} ALL=(ALL) ALL"  state=present create=yes validate='visudo -cf %s'

  - lineinfile: dest=/etc/ssh/sshd_config regexp='^UsePAM' line="UsePAM no"  state=present

  - lineinfile: dest=/etc/ssh/sshd_config state=present line="AllowUsers {{ sudoers }} root"

  - authorized_key: user={{ sudoers }}
                    key="{{ lookup('file', '/Users/shujinwu/.ssh/id_rsa.pub') }}"
                    state=present

  - name: restart ssh service
    service: name=sshd state=restarted