---
- hosts: coprhd
  sudo: yes
  gather_facts: no
  remote_user: root
  vars:
    sudoers:
      shujin 

  tasks:
  
  - name: Add user 
    user: name="{{ sudoers }}" state=present createhome=yes 

  - name: configure sudoers
    lineinfile: dest=/etc/sudoers line="{{ sudoers }} ALL=(ALL) ALL"  state=present create=yes validate='visudo -cf %s'
  
  - lineinfile: dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication' line="PasswordAuthentication yes"  state=present
 
  - lineinfile: dest=/etc/ssh/sshd_config regexp='^UsePAM' line="UsePAM no"  state=present

  - lineinfile: dest=/etc/ssh/sshd_config state=present line="AllowUsers {{ sudoers }} root"

  - authorized_key: user={{ sudoers }}
                    key="{{ lookup('file', '/Users/shujinwu/.ssh/id_rsa.pub') }}"
                    state=present

  - name: restart ssh service
    service: name=sshd state=restarted