---
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

  - name: install git
    zypper: name=git state=present disable_recommends=yes 

  - name: intall make
    zypper: name=make state=present disable_recommends=yes

  - name: git clone coprhd repo
    git: repo=https://review.coprhd.org/scm/ch/coprhd-controller.git dest=/root/coprhd-controller update=no

 # - name: execute the script to install addtional package repository
 #   command: bash /root/coprhd-controller/packaging/appliance-images/openSUSE/13.2/CoprHDDevKit/configure.sh installRepositories

#  - name: execute the script to install addtional rpm for coprHD - gonna take some time...
#   command: bash /root/coprhd-controller/packaging/appliance-images/openSUSE/13.2/CoprHDDevKit/configure.sh installPackages

#  - name: execute the script to install Patched Nginx server
 #   command: bash /root/coprhd-controller/packaging/appliance-images/openSUSE/13.2/CoprHDDevKit/configure.sh installNginx
  
  - name: install java 8
    zypper: name=java-1_8_0-openjdk state=present disable_recommends=yes disable_gpg_check=yes 

  - name: install java 8 devel
    zypper: name=java-1_8_0-openjdk-devel state=present disable_recommends=yes disable_gpg_check=yes
 
  - name: script to configure java 8
    command: bash /root/coprhd-controller/packaging/appliance-images/openSUSE/13.2/CoprHDDevKit/configure.sh installJava 8

  - name: create the storageOS user and group
    command: bash /root/coprhd-controller/packaging/appliance-images/openSUSE/13.2/CoprHDDevKit/configure.sh installStorageOS

  - name: copy ovfenv.properties
    copy: src=ovfenv.properties dest=/etc/ovfenv.properties 

  - name: create the default coprHD Network configuration file
    command: bash /root/coprhd-controller/packaging/appliance-images/openSUSE/13.2/CoprHDDevKit/configure.sh installNetworkConfigurationFile
