---
- hosts: coprhd-ingestion
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:
   
  - name: go to coprhd-controller folder and build prm   
    command: chdir=/root/coprhd-controller make clobber BUILD_TYPE=oss rpm
