---
- hosts: coprhd
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

  - name: git clone coprhd repo
    git: repo=https://review.coprhd.org/scm/ch/coprhd-controller.git dest=/root/coprhd-controller update=yes clone=yes version=de6886429da0d9c523fbd551952a4bf933ee5eed
 #ingestion branch 0962701acb0b8f72e47e1f109f59b451c431ca55   
  - name: go to coprhd-controller folder and build rpm  - takes within 10 mins 
    command: chdir=/root/coprhd-controller make clobber BUILD_TYPE=oss rpm
    register: output

  - debug: msg="{{output.stdout}}"

  - name: install coprhd rpm
    command: rpm -Uvh /root/coprhd-controller/build/RPMS/x86_64/*.rpm
    register: output

  - debug: msg="{{output.stdout}}"

  - name: enable root ssh
    lineinfile: dest=/etc/ssh/sshd_config state=present regexp="^PermitRootLogin" line="PermitRootLogin yes" insertafter="^2m"
