---
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

  - name: install git
    zypper: name=git state=present disable_recommends=yes 

  - name: intall make
    zypper: name=make state=present disable_recommends=yes
  
  - name: intall repositories
    zypper_repository: name=suse-13.2-oss repo=http://download.opensuse.org/distribution/13.2/repo/oss/suse state=present disable_gpg_check=yes refresh=yes

  - zypper_repository: name=suse-13.2-oss-update repo=http://download.opensuse.org/repositories/openSUSE:/13.2:/Update/standard state=present disable_gpg_check=yes refresh=yes

  - zypper_repository: name=suse-13.2-non-oss repo=http://download.opensuse.org/distribution/13.2/repo/non-oss/suse state=present disable_gpg_check=yes refresh=yes

  - zypper_repository: name=suse-13.2-monitoring repo=http://download.opensuse.org/repositories/server:/monitoring/openSUSE_13.2 state=present disable_gpg_check=yes refresh=yes

  - zypper_repository: name=suse-13.2-seife repo=http://download.opensuse.org/repositories/home:/seife:/testing/openSUSE_13.2 state=present disable_gpg_check=yes refresh=yes

  - zypper_repository: name=suse-13.2-python repo=http://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_13.2 state=present disable_gpg_check=yes refresh=yes

  - zypper_repository: name=suse-13.2-network repo=http://download.opensuse.org/repositories/network:/utilities/openSUSE_13.2 state=present disable_gpg_check=yes refresh=yes

  - zypper_repository: name=suse-13.2-building repo=http://download.opensuse.org/repositories/devel:/tools:/building/openSUSE_13.2 state=present disable_gpg_check=yes refresh=yes
  
  - zypper_repository: name=suse-13.2-appliances repo=http://download.opensuse.org/repositories/Virtualization:/Appliances/openSUSE_13.2 state=present disable_gpg_check=yes refresh=yes

  - zypper_repository: name=suse-13.2-containers repo=http://download.opensuse.org/repositories/Virtualization:/containers/openSUSE_13.2 state=present disable_gpg_check=yes refresh=yes

  # - zypper_repository: name=scalpel4k-opensuse repo=http://download.opensuse.org/repositories/home:/scalpel4k/openSUSE_Factory state=present disable_gpg_check=yes refresh=yes

  # - zypper_repository: name=VirtualBox-for-openSUSE13.2 repo=http://download.virtualbox.org/virtualbox/rpm/opensuse/13.2 state=present disable_gpg_check=yes refresh=yes

  - name: install Packages
    zypper: name=ant disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=apache2-mod_perl disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=apache2-prefork disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=atop disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=bind-libs disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=bind-utils disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=ca-certificates-cacert disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=ca-certificates-mozilla disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=curl disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=createrepo disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=dhcpcd disable_gpg_check=yes disable_recommends=yes state=present

# remove docker 
  - zypper: name=docker disable_gpg_check=yes disable_recommends=yes state=absent

  - zypper: name=docker-compose disable_gpg_check=yes disable_recommends=yes state=absent

  - zypper: name=expect disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=fontconfig disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=fonts-config disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=gcc-c++ disable_gpg_check=yes disable_recommends=yes state=present
  
  - zypper: name=GeoIP disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=GeoIP-data disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=git disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=git-core disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=glib2-devel disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=gpgme disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=grub2 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=ifplugd disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=inst-source-utils disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=iproute2 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=iputils disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=java-1_7_0-openjdk disable_gpg_check=yes disable_recommends=yes state=absent

  - zypper: name=java-1_7_0-openjdk-devel disable_gpg_check=yes disable_recommends=yes state=absent
  
  - name: install java 8
    zypper: name=java-1_8_0-openjdk disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=java-1_8_0-openjdk-devel disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=keepalived disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=kernel-default disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=kernel-default-devel disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=kernel-source disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=kiwi disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=kiwi-desc-isoboot disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=kiwi-desc-oemboot disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=kiwi-desc-vmxboot disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=kiwi-templates disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libaudiofile1 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libesd0 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libgcrypt-devel disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libGeoIP1 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libgpg-error-devel disable_gpg_check=yes disable_recommends=yes state=present 

  - zypper: name=libmng2 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libopenssl-devel disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libpcrecpp0 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libpcreposix0 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libqt4 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libqt4-sql disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libqt4-x11 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libSDL-1_2-0 disable_gpg_check=yes disable_recommends=yes state=present 

  - zypper: name=libserf-devel disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libtool disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libuuid-devel disable_gpg_check=yes disable_recommends=yes state=present

  - name: install libvpx1
    zypper: name=http://rpm.pbone.net/index.php3/stat/26/dist/97/size/1767471/name/libvpx-1.3.0-2.1.2.src.rpm disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libxml2-devel disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=libXmu6 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=lvm2 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=make disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=mkfontdir disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=mkfontscale disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=mozilla-nss-certs disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=netcfg disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=net-tools disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=ndisc6 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=nfs-client disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=openssh disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=openssh-fips disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=p7zip disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=pam-devel disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=parted disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=pcre-devel disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=perl-Config-General disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=perl-Error disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=perl-Tk disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=plymouth disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=python-cjson disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=python-devel disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=python-gpgme disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=python-iniparse disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=python-libxml2 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=python-py disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=python-requests disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=python-setools disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=qemu disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=qemu-tools disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=readline-devel disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=regexp disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=rpm-build disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=setools-libs disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=sipcalc disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=sshpass disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=strongswan disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=strongswan-ipsec disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=strongswan-libs0 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=subversion disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=sudo disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=SuSEfirewall2 disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=sysconfig disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=sysconfig-netconfig disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=syslinux disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=sysstat disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=systemd-logger disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=tar disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=telnet disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=unixODBC disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=vim disable_gpg_check=yes disable_recommends=yes state=present

  #disable virtualbox
  # - name: install virtualbox
  #   zypper: name=virtualbox disable_gpg_check=yes disable_recommends=yes state=present

  # - zypper: name=virtualbox-guest-kmp-default disable_gpg_check=yes disable_recommends=yes state=present

  # - zypper: name=virtualbox-host-kmp-default disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=wget disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=xbitmaps disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=xfsprogs disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=xml-commons-jaxp-1.3-apis disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=xmlstarlet disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=xorg-x11-essentials disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=xorg-x11-fonts disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=yum disable_gpg_check=yes disable_recommends=yes state=present

  - command: zypper update -y

  # - name: install xorg-x11-server 
  #   zypper: name=xorg-x11-server disable_gpg_check=yes disable_recommends=no state=present
  # - command: zypper install xorg-x11-server -2

  - zypper: name=xz-devel disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=zlib-devel disable_gpg_check=yes disable_recommends=yes state=present

  # docker - not needed
  - zypper: name=http://download.opensuse.org/update/13.2/src/docker-1.8.3-43.1.src.rpm disable_gpg_check=yes state=absent

  - zypper: name=http://download.opensuse.org/update/13.2/src/lvm2-2.02.98-43.24.1.src.rpm disable_gpg_check=yes state=present

  - zypper: name=http://download.opensuse.org/update/13.2/src/systemd-210.1448627060.53ee915-25.27.1.src.rpm disable_gpg_check=yes state=present

  - zypper: name=http://download.opensuse.org/update/13.2/src/systemd-210.1448627060.53ee915-25.27.1.src.rpm disable_gpg_check=yes state=present
  
  - name: choose java 8
    alternatives: name=java path=/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/bin/java

  - name: git clone coprhd repo
    git: repo=https://review.coprhd.org/scm/ch/coprhd-controller.git dest=/root/coprhd-controller update=no

  - name: execute the script to install Patched Nginx server
    command: bash /root/coprhd-controller/packaging/appliance-images/openSUSE/13.2/CoprHDDevKit/configure.sh installNginx



