---
- hosts: coprhd-master
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

  - name: git clone coprhd repo
    git: repo=https://review.coprhd.org/scm/ch/coprhd-controller.git dest=/root/coprhd-controller update=no clone=yes 
    # version=3d29e523932
    
  - name: go to coprhd-controller folder and build rpm   
    command: chdir=/root/coprhd-controller make clobber BUILD_TYPE=oss rpm
    register: output

  - debug: msg="{{output.stdout}}"

  - name: install coprhd rpm
    command: rpm -Uvh /root/coprhd-controller/build/RPMS/x86_64/*.rpm
    register: output

  - debug: msg="{{output.stdout}}"


