---
- hosts: coprhd
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

  - name: copy configure.sh
    copy: src=configure.sh dest=/root/configure.sh

  - name: execute the script to install addtional package repository
    command: bash /root/configure.sh installRepositories
    register: output

  - debug: msg="{{output.stdout}}"

  - name: execute the script to install addtional rpm for coprHD - gonna take some time...
    command: bash /root/configure.sh installPackages
    register: output

  - debug: msg="{{output.stdout}}"

  - name: execute the script to install Patched Nginx server
    command: bash /root/configure.sh installNginx
 
  - name: script to configure java 8
    command: bash /root/configure.sh installJava 8

  - name: create the storageOS user and group
    command: bash /root/configure.sh installStorageOS
    register: output

  - debug: msg="{{output.stdout}}"

  - name: copy ovfenv.properties
    copy: src=ovfenv.properties dest=/etc/ovfenv.properties 