---
- hosts: coprhd
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:
  
  - name: remove storageos
    command: rpm -e storageos
    # zypper: name=storageos state=absent

  - name: clean up /data
    file: path=/data state=absent

  - name: remove repo
    file: path=/root/coprhd-controller state=absent
