---
- hosts: coprhd
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

  - name: remove storageos
    zypper: name=storageos state=absent

  - name: clean up /data
    file: path=/data state=absent
