---
  - name: fetch controller-conf.xml
    fetch: src=/opt/storageos/conf/controller-conf.xml dest=../driver-confs/controller-conf.xml flat=yes
# /Users/shujinwu/tmp/
  - name: fetch discovery-externaldevice-context.xml
    fetch: src=/opt/storageos/conf/discovery-externaldevice-context.xml dest=../driver-confs/discovery-externaldevice-context.xml flat=yes

  - name: fetch /opt/storageos/cli/bin/storagesystem.py
    fetch: src=/opt/storageos/cli/bin/storagesystem.py dest=../driver-confs/storagesystem.py flat=yes

  - name: fetch controllersvc
    fetch: src=/opt/storageos/bin//controllersvc-debug dest=../driver-confs/controllersvc flat=yes