---
  ############################################################################
  #
  #  Install java 8
  #
  ############################################################################
  - zypper: name=java-1_7_0-openjdk disable_gpg_check=yes disable_recommends=yes state=absent

  - zypper: name=java-1_7_0-openjdk-devel disable_gpg_check=yes disable_recommends=yes state=absent

  - name: install java 8
    zypper: name=java-1_8_0-openjdk disable_gpg_check=yes disable_recommends=yes state=present

  - zypper: name=java-1_8_0-openjdk-devel disable_gpg_check=yes disable_recommends=yes state=present

  - name: choose java 8
    alternatives: name=java path=/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/bin/java